name: "CI Filter"
description: "Filter CI jobs based on changed files"

inputs:
  filters:
    description: "The filters to use"
    required: false
    default: |
      files:
        - 'packages/**/*.{ts,tsx,js,jsx,json}'
        - 'yarn.lock'

outputs:
  files:
    description: "Whether files were changed"
    value: ${{ steps.filter.outputs.files }}

runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@v2.11.1
      id: filter
      with:
        filters: ${{ inputs.filters }}
