name: "CI Base"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
