name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn prestart:ci

  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: |
            files:
              - 'packages/**/*.{ts,tsx,js,jsx,json}'
              - 'yarn.lock'

      - uses: actions/cache@v3
        if: ${{ steps.filter.outputs.files == 'true' }}
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        if: ${{ steps.filter.outputs.files == 'true' }}
        run: yarn build

  test:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - uses: ./.github/actions/ci-filter
        id: filter

      - uses: actions/cache@v3
        if: ${{ steps.filter.outputs.files == 'true' }}
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Test
        if: ${{ steps.filter.outputs.files == 'true' }}
        run: yarn test
