name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn prestart:ci

  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: |
            files:
              - 'packages/**/*.{ts,tsx,js,jsx,json}'
      - uses: actions/cache@v3
        if: ${{ steps.filter.outputs.files == 'true' }}
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        if: ${{ steps.filter.outputs.files == 'true' }}
        run: yarn build

  test:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: |
            files:
              - 'packages/**/*.{ts,tsx,js,jsx,json}'

      - uses: actions/cache@v3
        if: ${{ steps.filter.outputs.files == 'true' }}
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Test
        if: ${{ steps.filter.outputs.files == 'true' }}
        run: yarn test
